---
- name: Configure Internet Pi.
  hosts: internet_pi
  become: true
  vars:
    config_dir: "{{ config.config_dir }}"
    dns_servers: "{{ config.dns_servers }}"
    domain: "{{ config.domain }}"
    services: "{{ config.services | dict2items | rejectattr('value.enable', 'defined') | list | union( config.services | dict2items | selectattr('value.enable', 'defined') | rejectattr('value.enable', 'equalto', false) | list ) | items2dict }}"
    enabled_services: "{{ config.services | dict2items | rejectattr('value.enable', 'defined') | list | union( config.services | dict2items | selectattr('value.enable', 'defined') | rejectattr('value.enable', 'equalto', false) | list ) | map('combine', {'value': true}) | list | union(config.services | dict2items | selectattr('value.enable', 'defined') | selectattr('value.enable', 'equalto', false) | map('combine', {'value': false}) | list) | items2dict }}"


  pre_tasks:
    - name: Load configuration.
      ansible.builtin.include_vars:
        file: config.yml
        name: config

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: System configuration.
      ansible.builtin.import_tasks: tasks/system.yml

    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up Internet Monitoring.
      ansible.builtin.import_tasks: tasks/internet-monitoring.yml
      when:
        - enabled_services.monitoring

    - name: Set up Pi Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when:
        - enabled_services.pihole

    - name: Set up Shelly Plug Monitoring.
      ansible.builtin.import_tasks: tasks/shelly-plug.yml
      when:
        - enabled_services.shelly_plug

    - name: Set up Air Gradient Monitoring.
      ansible.builtin.import_tasks: tasks/airgradient.yml
      when:
        - enabled_services.airgradient

    - name: Set up Timetagger.
      ansible.builtin.import_tasks: tasks/timetagger.yml
      when:
        - enabled_services.timetagger

    - name: Set up Homepage.
      ansible.builtin.import_tasks: tasks/homepage.yml
      when:
        - enabled_services.homepage

    - name: Set up Home Assistant.
      ansible.builtin.import_tasks: tasks/home-assistant.yml
      when:
        - enabled_services.homeassistant
