---
- name: Restart pi-hole
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/pi-hole/"
    remove_orphans: true
    build: never
    state: restarted
  become: false

- name: Restart internet-monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/internet-monitoring/"
    remove_orphans: true
    build: never
    state: restarted
  become: false

- name: Restart shelly-plug-prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/shelly-plug-prometheus/"
    remove_orphans: true
    build: never
    state: restarted
  become: false

- name: Restart timetagger
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/timetagger/"
    remove_orphans: true
    build: never
    state: restarted
  become: false

- name: Restart homepage
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/homepage/"
    remove_orphans: true
    build: never
    state: restarted
  become: false

- name: Restart Home Assistant
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/homeassistant/"
    remove_orphans: true
    build: never
    state: restarted
  become: false
