---
- name: Ensure Homepage directory exists.
  file:
    path: "{{ config_dir }}/homepage"
    state: directory
    mode: 0755
  become: false
  register: homepage_dir

- name: Ensure Homepage supporting directories exist.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ homepage_dir.path }}/config"
    - "{{ homepage_dir.path }}/images"
  become: false

- name: Copy Homepage background image.
  ansible.builtin.copy:
    src: images/homepage-background.png
    dest: "{{ homepage_dir.path }}/images/homepage-background.png"
    mode: '0640'
  become: false

- name: Set Homepage settings.
  lineinfile:
    dest: "{{ homepage_dir.path }}/config/settings.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^title:"
      line: "title: {{ services.homepage.title }}"
    - regexp: "^description:"
      line: "description: {{ services.homepage.description }}"
    - regexp: "^startUrl:"
      line: "startUrl: {{ services.homepage.startUrl }}"
    - regexp: "^background:"
      line: "background: {{ services.homepage.background }}"
    - regexp: "^theme:"
      line: "theme: {{ services.homepage.theme }}"
    - regexp: "^color:"
      line: "color: {{ services.homepage.color }}"
    - regexp: "^useEqualHeights:"
      line: "useEqualHeights: {{ services.homepage.useEqualHeights }}"
    - regexp: "^headerStyle:"
      line: "headerStyle: {{ services.homepage.headerStyle }}"
    - regexp: "^target:"
      line: "target: {{ services.homepage.target }}"
    - regexp: "^hideVersion:"
      line: "hideVersion: {{ services.homepage.hideVersion }}"
  become: false

- name: Copy Homepage services.yml to Pi.
  ansible.builtin.template:
    src: templates/homepage-services.yaml.j2
    dest: "{{ homepage_dir.path }}/config/services.yaml"
    mode: '0644'
  become: false
  vars:
    devices: "{{ services.homepage.devices }}"
    utilities: "{{ services | json_query('*.homepage.utilities') | flatten }}"
    applications: "{{ services | json_query('*.homepage.applications') | flatten }}"

- name: Copy Homepage docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/homepage-docker-compose.yml.j2
    dest: "{{ homepage_dir.path }}/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart homepage

- name: Ensure Homepage is running.
  community.docker.docker_compose_v2:
    project_src: "{{ homepage_dir.path }}/"
    build: never
  become: false
